    # print("Highest loss movie:", highest_loss_movie())
    # print("---------------------------------------------")
    # print("Actor with the longest name:", actor_longest_name())
    # print("---------------------------------------------")
    # print("Movie with the shortest title:", shortest_movie_title())
    # print("---------------------------------------------")
    # print("Most expensive movie per time:", most_expensive_movie_per_time())
    # print("---------------------------------------------")
    # print("Lowest budget movie with popularity >= 10:", lowest_budget_popularity())
    # print("---------------------------------------------")
    # print("Highest revenue movie with popularity <= 1:", highest_revenue_popularity_lte_1())